### ISSUE TITLE
Add ability to toggle manually

### ISSUE THREAD

**Issue by kristijanhusak** [jikamens/bt_pa_auto_switcher#3]
Hi,

I started using this from the last fix, and sometimes it works, sometimes it doesn't. I need to reconnect the Bluetooth connection to make it work sometimes. Can't really reproduce it 100% of the time.

I would like to have a script where I would just execute it and it would toggle the mode. That way I can just do it manually when needed.

Something like `bt_pa_auto_switcher --hfp` and `bt_pa_auto_switcher --a2dp`

**Comment by jikamens** [comment]
Can't you just use the settings app to do this?

**Comment by kristijanhusak** [comment]
Yeah that's what i'm currently doing. Going into the app before and after every meeting to toggle it back and forth. I just thought that having it as a script would be more straightforward.

**Comment by kristijanhusak** [comment]
I found a script that can handle this for me: https://gist.github.com/OndraZizka/2724d353f695dacd73a50883dfdf0fc6

So no need for this. Thanks anyway.
